### ISSUE TITLE
Command to open the GUI?

### ISSUE THREAD

**Issue by TechPlayHD** [j0ach1mmall3/UltimateCosmetics#123]
Hey,

waht is the command to open the gui, i search it on the complete site :3

Thank for an answer and sorry for my bad english!

~ TechPlayHD

**Comment by TechPlayHD** [comment]
Does not go and is to new ones the following error message still comes: 
http://prnt.sc/ahpwpz

Even of the DeBug fashion does not go:O

**Comment by j0ach1mmall3** [comment]
You are on 1.8? Atm uc doesn't work for 1.8, I can post an update now if you wish?

**Comment by TechPlayHD** [comment]
Yes PLEASE :3
:+1:

**Comment by TechPlayHD** [comment]
Is this the Update?

http://prntscr.com/ahqreb

**Comment by j0ach1mmall3** [comment]
Yes

**Comment by TechPlayHD** [comment]
Thank you verry much!

**Comment by TechPlayHD** [comment]
But it is still not unfortunately :(

**Comment by j0ach1mmall3** [comment]
What does it say?

**Comment by TechPlayHD** [comment]
If I liked to begin the DeBug mode, stands like with every Command of UC "/uc <argument>" in the chat and in the console / log no mistake stands also! :/

**Comment by maxlehot1234** [comment]
Try disabling 1.9 feature like auras and balloons.

It works for me, this is my config file: http://pastebin.com/Q6QnAGTC

Do you put the config_1.8 folder content inde the ultimatescosmetics folder if you run 1.8 server?

**Comment by TechPlayHD** [comment]
It doesn't work :(

**Comment by j0ach1mmall3** [comment]
What's the error then?
"It doesn't work" doesn't help me
Provide me logs...

**Comment by TechPlayHD** [comment]
`Error occurred while enabling UltimateCosmetics v4.0.4 (Is it up to date?) 
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_CHEST_OPEN 
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_74] 
at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot.jar:git-Spigot-5f38d38-18fbb24] 
at com.j0ach1mmall3.ultimatecosmetics.config.Config.<init>(Config.java:62) ~[?:?] 
at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:92) ~[?:?] 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-5f38d38-18fbb24] 
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-18fbb24] 
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] `

**Comment by TechPlayHD** [comment]
#OPEN

**Comment by j0ach1mmall3** [comment]
M8
Did you even read what maxlehot said?

**Comment by TechPlayHD** [comment]
Yes :c

**Comment by maxlehot1234** [comment]
@TechPlayHD 
You try to use 1.9 sounds in 1.8 servers...
All was in the error...

Use : CHEST_OPEN instead

Here is the link for 1.8 sounds: https://www.spigotmc.org/wiki/cc-sounds-list/
Check middle of the page, NOT TOP

**Comment by j0ach1mmall3** [comment]
Or use the config files in the config_1.8 folder in the jar

**Comment by TechPlayHD** [comment]
can not have both :/
