### ISSUE TITLE
Ultimate Cosmetics not working with bungeetablistplus

### ISSUE THREAD

**Issue by TheSander562** [j0ach1mmall3/UltimateCosmetics#128]
I have a problem with the aura's.
If I select a random aura bungeetablistplus throws out errors about the scoreboard.
And then you cant do anything in the server and you cant connect to it.
I hope you can fix this.

**Comment by j0ach1mmall3** [comment]
/uc debug
Error log aswell

**Comment by TheSander562** [comment]
the uc debug:
https://gist.github.com/anonymous/4cc22a44dd761cfa0971

And it keeps spamming this code when I click on a aura:
23:09:12 [WARNING] [BungeeTabListPlus] An error has occurred while handling a scoreboard packet. This is a serious issue and may lead to a client crash. The issue is caused by one of you bukkit plugins.
java.lang.IllegalArgumentException: Team 4gSC3XGONuwc3uCy already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:186)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:102)
	at codecrafter47.bungeetablistplus.packet.v1_8.TeamPacket.handle(TeamPacket.java:90)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)

**Comment by j0ach1mmall3** [comment]
No way for me to fix it unfortunately, you'll probably have to disable Auras :(

**Comment by j0ach1mmall3** [comment]
Duplicate of #120
