### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Mineteamhost** [j0ach1mmall3/UltimateCosmetics#132]
Hello,
I have a problem.
I download the source code, import it into Eclipse and I compile it as .jar file.
I put the .jar file into plugin folder of my server.
When i start the server, it gives this error:
[20:55:30 ERROR]: Could not load 'plugins/cosmetics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.j0ach1mmall3.ultimatecosmetics.Main.java'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: com.j0ach1mmall3.ultimatecosmetics.Main.java
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_73]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 7 more
Thank 
Mineteam

P.S.: Sorry for my bad english. I'm Italian.

**Comment by j0ach1mmall3** [comment]
As mentioned in the thread, I don't offer support for non-buying owners
