### ISSUE TITLE
The plugin does not start

### ISSUE THREAD

**Issue by xTechnoCat** [j0ach1mmall3/UltimateCosmetics#135]
[20:22:44] [Server thread/INFO]: [UltimateCosmetics] Enabling UltimateCosmetics v4.0.4
[20:22:44] [Server thread/ERROR]: Error occurred while enabling UltimateCosmetics v4.0.4 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_CHEST_OPEN
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.j0ach1mmall3.ultimatecosmetics.config.Config.<init>(Config.java:62) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:92) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by j0ach1mmall3** [comment]
Use the 1.8 configs in the config_1.8 folder
