### ISSUE TITLE
How to run the plugin on 1.8.8?

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#150]
Hello I get this plugin at the moment I want to run it

`
[19:34:23] [Server thread/INFO]: [UltimateCosmetics] ^[[0;32;1mLoading Modules...^[[m
[19:34:23] [Server thread/ERROR]: Error occurred while enabling UltimateCosmetics v4.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/j0ach1mmall3/jlib/plugin/JlibPlugin
        at com.j0ach1mmall3.ultimatecosmetics.modules.bowtrails.BowTrailsModule.onEnable(BowTrailsModule.java:27) ~[?:?]
        at com.j0ach1mmall3.jlib.plugin.modularization.PluginModule.setEnabled(PluginModule.java:47) ~[?:?]
        at com.j0ach1mmall3.ultimatecosmetics.Main.loadModules(Main.java:435) ~[?:?]
        at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:180) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: com.j0ach1mmall3.jlib.plugin.JlibPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        ... 15 more
`

I already changed the  sound values plus, all files are not getting generated
http://i.cgm.rs/i/MobaXterm_2016-04-27_18-40-33.png

**Comment by j0ach1mmall3** [comment]
Are you on the latest versions of everything?

**Comment by IlPicasso** [comment]
Yes

**Comment by maxlehot1234** [comment]
It is an issue with latest jlib version... because it works before, but kick me each time I open the gui, so I try to update jlib and ultiumatecosmetics and now I can't use them :( :(

**Comment by j0ach1mmall3** [comment]
Fixed in 4.1.1
