### ISSUE TITLE
Plugin won't enable

### ISSUE THREAD

**Issue by chickenputty** [j0ach1mmall3/UltimateCosmetics#163]
The plugin will not enable.

Error log:
```
[23:33:53] [Server thread/INFO]: Starting minecraft server version 1.8.8
[23:33:53] [Server thread/INFO]: Loading properties
[23:33:53] [Server thread/INFO]: Default game type: SURVIVAL
[23:33:53] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:33:53] [Server thread/INFO]: Debug logging is disabled
[23:33:53] [Server thread/INFO]: Server Ping Player Sample Count: 12
[23:33:53] [Server thread/INFO]: Using 4 threads for Netty based IO
[23:33:53] [Server thread/INFO]: Generating keypair
[23:33:53] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:33:53] [Server thread/INFO]: Using default channel type
[23:33:54] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[23:33:54] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.6.5
[23:33:54] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v9.0.6
[23:33:54] [Server thread/INFO]: [JLib] Loading JLib v4.9.1
[23:33:54] [Server thread/INFO]: [UltimateCosmetics] Loading UltimateCosmetics v4.1.2
[23:33:54] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.5
[23:33:54] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[23:33:54] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[23:33:54] [Server thread/INFO]: Preparing level "world"
[23:33:54] [Server thread/INFO]: Preparing start region for level 0 (Seed: 7409612468006209415)
[23:33:55] [Server thread/INFO]: Preparing start region for level 1 (Seed: 7409612468006209415)
[23:33:55] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.0.6
[23:33:55] [Server thread/INFO]: [LibsDisguises] Discovered MC version: v1_8_R3
[23:33:55] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.0.6 (Is it up to date?)
java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
    at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerViewDisguises.<init>(PacketListenerViewDisguises.java:31) ~[?:?]
    at me.libraryaddict.disguise.utilities.PacketsManager.init(PacketsManager.java:626) ~[?:?]
    at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:63) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[23:33:55] [Server thread/INFO]: [JLib] Enabling JLib v4.9.1
[23:33:55] [Server thread/INFO]: [JLib] [0;31;1mVault not found, some placeholders may not work![m
[23:33:55] [Server thread/INFO]: [JLib] [0;33;22mPlaceholderAPI not found, switching over to default Placeholders[m
[23:33:55] [Server thread/INFO]: [UltimateCosmetics] Enabling UltimateCosmetics v4.1.2
[23:33:55] [Server thread/ERROR]: Error occurred while enabling UltimateCosmetics v4.1.2 (Is it up to date?)
java.lang.NullPointerException
    at com.j0ach1mmall3.ultimatecosmetics.config.Config.<init>(Config.java:62) ~[?:?]
    at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:97) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[23:33:55] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:33:55] [Server thread/INFO]: Done (1.581s)! For help, type "help" or "?"
[23:33:56] [Craft Scheduler Thread - 1/INFO]: [JLib] [0;32;1mYou are up to date![m
[23:34:14] [Server thread/INFO]: [0;32;1mLibsDisguises[0;37;1m version [0;32;1m9.0.6[m
[23:34:14] [Server thread/INFO]: A disguise plugin with various disguises.[m
[23:34:14] [Server thread/INFO]: Authors: [0;32;1mlibraryaddict[0;37;1m, [0;32;1mByteflux[0;37;1m and [0;32;1mNavid K.[m
[23:34:21] [Server thread/INFO]: [0;32;1mProtocolLib[0;37;1m version [0;32;1m3.6.5[m
[23:34:21] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.[m
[23:34:21] [Server thread/INFO]: Authors: [0;32;1mdmulloy2[0;37;1m and [0;32;1mcomphenix[m
[23:34:26] [Server thread/INFO]: [0;32;1mJLib[0;37;1m version [0;32;1m4.9.1[m
[23:34:26] [Server thread/INFO]: Main Library for j0ach1mmall3 Plugins[m
[23:34:26] [Server thread/INFO]: Author: [0;32;1mj0ach1mmall3[m
[23:34:30] [Server thread/INFO]: [0;32;1mUltimateCosmetics[0;37;1m version [0;32;1m4.1.2[m
[23:34:30] [Server thread/INFO]: Featuring over 20 different Cosmetics Types, endless possibilities![m
[23:34:30] [Server thread/INFO]: Author: [0;32;1mj0ach1mmall3[m
[23:34:37] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)[m
[23:34:37] [Server thread/INFO]: Checking version, please wait...[m
[23:34:38] [Thread-8/INFO]: You are 263 version(s) behind[m
[23:34:44] [Server thread/INFO]: Stopping the server
[23:34:44] [Server thread/INFO]: Stopping server
[23:34:44] [Server thread/INFO]: [UltimateCosmetics] Disabling UltimateCosmetics v4.1.2
[23:34:44] [Server thread/INFO]: [JLib] Disabling JLib v4.9.1
[23:34:44] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v9.0.6
[23:34:44] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v3.6.5
[23:34:44] [Server thread/INFO]: Saving players
[23:34:44] [Server thread/INFO]: Saving worlds
[23:34:44] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[23:34:45] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
```
Plugins and versions:
![Image](http://puttyland.com/share/nI9IkGHf.png)

JLib v4.9.1 debug dump:
https://gist.github.com/anonymous/634f90272ff73ca37841f66def492245

Config:
```
# ######################################################################################## #
# UltimateCosmetics version 4.X.X configuration                                            #
# Any help with this configuration should be requested here:                               #
# https://www.spigotmc.org/threads/ultimatecosmetics.60528/                                #
# (c) 2016 j0ach1mmall3 - All rights reserved                                              #
# ######################################################################################## #

# Should the plugin check for updates on Spigot
UpdateChecker: true
# The logging level, can be ALL, EXTENDED, NORMAL, MINIMAL, NOTHING
LogLevel: EXTENDED
# Should Cosmetics be removed when a player changes worlds?
RemoveCosmeticsOnWorldChange: false
# Should Cosmetics be removed when a player logs out?
RemoveCosmeticsOnLogOut: false
# The worlds in which this plugin will not work
# Make sure RemoveCosmeticsOnWorldChange is set to true for this to work correctly
WorldsBlacklist:
- someworld
- someotherworld
# Should an Item be given upon joining, that will display the GUI upon clicking? (It is advised to turn this off in a non-hub environment)
GiveItemOnJoin: true
JoinItem:
    # The item format of the item (More info here: https://github.com/j0ach1mmall3/JLib/wiki/The-new-Item-Format)
    Item: '54 name:&1C&2o&3s&4m&5e&6t&7i&8c&9s lore:&7&oAmazing_Cosmetics!'
    # The slot in which the item will be put
    Position: 3
# The Sound to be played when a player opens the GUI (leave blank for no sound) A list of valid sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
GUIOpenSound:
# The Sound to be played when a player clicks in the GUI (leave blank for no sound) A list of valid sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
GUIClickSound:
# The command that will open the Cosmetics GUI
CosmeticsCommand: /cosmetics
CosmeticsGUI:
    # The inventory name of the Cosmetics GUI
    Name: '&1C&2o&3s&4m&5e&6t&7i&8c&9s'
    # The size of the Cosmetics GUI (must be divisible by 9!)
    Size: 45
    Items:
        AurasItem:
            # The item format of the item
            Item: '95:14 name:&1&lAuras lore:&7&oShow_everyone_who''s_important!'
            # The position in the GUI of this item (starts at 0)
            Position: 1
            #The command to be executed when you click on the item. Generally, this is the same command as defined in the Cosmetic's config, however, there are plenty of other options.
            Command: /auras
        BalloonsItem:
            Item: '420 name:&2&lBalloons lore:&7&oGet_yourself_a_lovely_Balloon!'
            Position: 3
            Command: /balloons
        BannerCapesItem:
            Item: '425:8 name:&3&lBanner_Capes itemflag:hide_potion_effects lore:&7&oWalk_around_with_a_stylish_Cape! pattern_cross:red'
            Position: 5
            Command: /bannercapes
        BannersItem:
            Item: '425:3 name:&4&lBanners itemflag:hide_potion_effects lore:&7&oPut_an_amazing_Banner_on_your_head! pattern_creeper:blue'
            Position: 7
            Command: /banners
        BlockPetsItem:
            Item: '91 name:&5&lBlock_Pets lore:&7&oBefriend_the_Blocks!'
            Position: 9
            Command: /blockpets
        BowTrailsItem:
            Item: '261 name:&6&lBowtrails lore:&7&oKill_your_opponents_in_style!'
            Position: 11
            Command: /bowtrails
        CloaksItem:
            Item: '116 name:&7&lCloaks lore:&7&oEquip_yourself_some_mystical_Cloaks!'
            Position: 15
            Command: /cloaks
        FireworksItem:
            Item: '401 name:&8&lFireworks lore:&7&oLight_off_some_celebration_Fireworks!'
            Position: 17
            Command: /fireworks
        GadgetsItem:
            Item: '369 name:&9&lGadgets lore:&7&oGet_hold_of_some_cool_Gadgets!'
            Position: 21
            Command: /gadgets
        HatsItem:
            Item: '310 name:&a&lHats itemflag:hide_attributes lore:&7&oShow_the_world_your_new_Hats!'
            Position: 23
            Command: /hats
        HeartsItem:
            Item: '351:1 name:&b&lHearts lore:&7&oCustomize_your_Hearts!'
            Position: 27
            Command: /hearts
        MorphsItem:
            Item: '397:4 name:&c&lMorphs lore:&7&oScare_your_friends_as_a_Creeper!'
            Position: 29
            Command: /morphs
        MountsItem:
            Item: '329 name:&d&lMounts lore:&7&oBecause_walking_is_mainstream!'
            Position: 33
            Command: /mounts
        MusicItem:
            Item: '2258 name:&1&lMusic itemflag:hide_potion_effects lore:&7&oListen_to_some_funky_Music!'
            Position: 35
            Command: /music
        ParticlesItem:
            Item: '399 name:&2&lParticles lore:&7&oLet_Particles_fly_around_you!'
            Position: 37
            Command: /particles
        PetsItem:
            Item: '383:90 name:&3&lPets lore:&7&oFriends_for_life!'
            Position: 39
            Command: /pets
        TrailsItem:
            Item: '362 name:&4&lTrails lore:&7&oLeave_a_trail_of..._Anything!'
            Position: 41
            Command: /trails
        WardrobeItem:
            Item: '299 name:&5&lWardrobe itemflag:hide_attributes lore:&7&oShow_off_some_beautiful_clothes!'
            Position: 43
            Command: /wardrobe
# Which Cosmetics should be enabled
Cosmetics:
  # Requires MC 1.9 or above
  Auras: false
  Balloons: false
  # Requires MC 1.8 or above
  BannerCapes: true
  # Requires MC 1.8 or above
  Banners: true
  BlockPets: true
  BowTrails: true
  Cloaks: true
  Fireworks: true
  Gadgets: true
  Hats: true
  Hearts: true
  # Requires LibsDisguises
  Morphs: true
  Mounts: true
  Music: true
  Particles: true
  Pets: true
  Trails: true
  Wardrobe: true
DoNotChange: 4.0.0
```
Removed sounds and disabled 1.9 features.

**Comment by j0ach1mmall3** [comment]
Balloons don't require 1.9
Pretty sure you need an older libsdisguises/protocollib version

**Comment by chickenputty** [comment]
You're right. I have no idea what version combinations of LibDisguises and ProtocolLib I was trying for hours.

It's erroring on the config now though:
```
[03:16:33] [Server thread/INFO]: Starting minecraft server version 1.8.8
[03:16:33] [Server thread/INFO]: Loading properties
[03:16:33] [Server thread/INFO]: Default game type: SURVIVAL
[03:16:33] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[03:16:33] [Server thread/INFO]: Debug logging is disabled
[03:16:33] [Server thread/INFO]: Server Ping Player Sample Count: 12
[03:16:33] [Server thread/INFO]: Using 4 threads for Netty based IO
[03:16:33] [Server thread/INFO]: Generating keypair
[03:16:33] [Server thread/INFO]: Starting Minecraft server on *:25565
[03:16:33] [Server thread/INFO]: Using default channel type
[03:16:33] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[03:16:33] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.6.5
[03:16:34] [Server thread/INFO]: [LibsDisguises] Loading LibsDisguises v8.6.8
[03:16:34] [Server thread/INFO]: [JLib] Loading JLib v4.9.1
[03:16:34] [Server thread/INFO]: [UltimateCosmetics] Loading UltimateCosmetics v4.1.2
[03:16:34] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.5
[03:16:34] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[03:16:34] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[03:16:34] [Server thread/INFO]: Preparing level "world"
[03:16:34] [Server thread/INFO]: Preparing start region for level 0 (Seed: 7409612468006209415)
[03:16:34] [Server thread/INFO]: Preparing start region for level 1 (Seed: 7409612468006209415)
[03:16:35] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v8.6.8
[03:16:35] [Server thread/INFO]: [JLib] Enabling JLib v4.9.1
[03:16:35] [Server thread/INFO]: [JLib] [0;31;1mVault not found, some placeholders may not work![m
[03:16:35] [Server thread/INFO]: [JLib] [0;33;22mPlaceholderAPI not found, switching over to default Placeholders[m
[03:16:35] [Server thread/INFO]: [UltimateCosmetics] Enabling UltimateCosmetics v4.1.2
[03:16:35] [Server thread/ERROR]: Error occurred while enabling UltimateCosmetics v4.1.2 (Is it up to date?)
java.lang.NullPointerException
	at com.j0ach1mmall3.ultimatecosmetics.config.Config.<init>(Config.java:62) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:97) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[03:16:35] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:16:35] [Server thread/INFO]: Done (1.494s)! For help, type "help" or "?"
[03:16:35] [Craft Scheduler Thread - 1/INFO]: [JLib] [0;32;1mYou are up to date![m
```

**Comment by chickenputty** [comment]
No errors with my config in a YAML parser.

**Comment by j0ach1mmall3** [comment]
You can't just remove the sounds, use the config files from the jar (they're in there)

**Comment by chickenputty** [comment]
The config says:
> The Sound to be played when a player clicks in the GUI **(leave blank for no sound)**

Anyways, using the 1.8 configs worked. Thanks.
(Very frustrating undocumented installation process to be honest)

**Comment by j0ach1mmall3** [comment]
Ah, I'll fix that issue. If you'd have installed the right libsdisguises/protocollib version, it'd been sped up quite a lot though. Maybe I'll add that to the page
