### ISSUE TITLE
Unknown Error on reload

### ISSUE THREAD

**Issue by EthanRPro** [j0ach1mmall3/UltimateCosmetics#165]
[06:24:36] [Server thread/INFO]: EthanRAdmin issued server command: /uc reload
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;33;22mRemoving Cosmetics on World change is not enabled! Players will keep their Cosmetics when they change Worlds![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;33;22mRemoving Cosmetics on logout is not enabled! Players will keep their Cosmetics when they log out![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;31;1mMorphs are enabled in the config, but LibsDisguises isn't installed. Adjusting that value.[m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mMain config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mLanguage config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mMisc config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mLoading Modules...[m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mBalloons config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mBannerCapes config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mBanners config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mBlockPets config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mBowTrails config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mCloaks config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mFireworks config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mGadgets config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mHats config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mHearts config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mMounts config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mMusic config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mParticles config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mPets config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mTrails config successfully loaded![m
[06:24:36] [Server thread/INFO]: [UltimateCosmetics] [0;32;1mOutfits config successfully loaded![m
[06:24:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'uc' in plugin UltimateCosmetics v4.1.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-6d0ae89-a03743b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_77]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_77]
	at com.j0ach1mmall3.ultimatecosmetics.Main.reload(Main.java:223) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.commands.UltimateCosmeticsCommandHandler.handleCommand(UltimateCosmeticsCommandHandler.java:38) ~[?:?]
	at com.j0ach1mmall3.jlib.commands.CommandHandler.onCommand(CommandHandler.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6d0ae89-a03743b]
	... 15 more

**Comment by j0ach1mmall3** [comment]
Make sure you're on the latest version
