### ISSUE TITLE
1.9 Bugs

### ISSUE THREAD

**Issue by MinecraftB0ss** [j0ach1mmall3/UltimateCosmetics#171]
Not sure if this is a known bug or a oversight on my end, but the enderman warp only isnt really teleporting the player, it moves them to the next block if they are lucky, most of the time just turns their view

The paint gun/trail replaces entities, such as skulls. on replacement it puts default data back. Possibly disable these items altering entities?

on gadgets, when removing CATapult, it breaks the fungun ability, error: 
`[23:41:55] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to UltimateCosmetics v4.1.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:779) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityProjectile.m(EntityProjectile.java:168) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.World.g(World.java:1592) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.j0ach1mmall3.ultimatecosmetics.modules.gadgets.Gadgets.getSound(Gadgets.java:76) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.modules.gadgets.GadgetsListener.onProjectileHit(GadgetsListener.java:565) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	... 14 more`

**Comment by j0ach1mmall3** [comment]
1. Endermen can't really be fixed unless I use NMS for Pets
2. The skulls aren't entities, and the changing should be clientside
3. Don't remove gadgets

**Comment by MinecraftB0ss** [comment]
So i cannot disable certain gadgets? or is there a different way to do that?

**Comment by j0ach1mmall3** [comment]
Mhmm what about changing the slot?

**Comment by MinecraftB0ss** [comment]
thats what i did, although i removed the page items, just a bit of a hacky solution though.
