### ISSUE TITLE
Issues with 1.7

### ISSUE THREAD

**Issue by Kira07** [j0ach1mmall3/UltimateCosmetics#179]
Using paperspigot 1.7.10 protocolhack.

This error is spamming on player login:
`[06:35:09] [Server thread/ERROR]: [JLib] Unhandled exception occured in onPacketSending(PacketEvent) for JLib
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_91]
	at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:455) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.events.PacketContainer.getPlayerInfoAction(PacketContainer.java:771) ~[ProtocolLib.jar:3.6.5-b222]
	at com.j0ach1mmall3.jlib.player.tagchanger.TagChanger.onPacketSending(TagChanger.java:43) ~[JLib%20(3).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.packetQueued(ShadedProtocolInjector.java:312) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector.onPacketSending(ShadedProtocolInjector.java:278) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.processSending(ShadedChannelInjector.java:400) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector.access$500(ShadedChannelInjector.java:81) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$5.handleScheduled(ShadedChannelInjector.java:366) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelInjector$5.onMessageScheduled(ShadedChannelInjector.java:334) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedChannelProxy$2.schedulingRunnable(ShadedChannelProxy.java:127) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.shaded.ShadedEventLoopProxy.execute(ShadedEventLoopProxy.java:95) [ProtocolLib.jar:3.6.5-b222]
	at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.handle(NetworkManager.java:129) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.sendPacket(PlayerConnection.java:807) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:328) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:185) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot.jar:git-PaperSpigot-1f7d532]
[06:35:09] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo@287b1cd5[
    action=0
    player=net.minecraft.util.com.mojang.authlib.GameProfile@14b40ed5[id=e5fed803-9d35-37d2-a72e-cd0d6acee232,name=Kiranyx,properties={textures=[net.minecraft.util.com.mojang.authlib.properties.Property@2370faf7]},legacy=false]
    gamemode=1
    ping=0
    username=Kiranyx
    timestamp=1468557309368
  ]`

This aswell:

`[06:35:09] [Server thread/WARN]: [UltimateCosmetics] Task #49 for UltimateCosmetics v4.2.0 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/NameTagVisibility
	at com.j0ach1mmall3.ultimatecosmetics.HiddenPlayersRunnable.run(HiddenPlayersRunnable.java:25) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [Spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.NameTagVisibility
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[Spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-PaperSpigot-1f7d532]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 8 more`

**Comment by j0ach1mmall3** [comment]
Install an older protocollib version

**Comment by Kira07** [comment]
Tried older protocollib versions and still can't get the plugin to work in 1.7.10 protocolhack.

And for the 1.7.10 being old: https://www.youtube.com/watch?v=oyJwQvbTWZM
