### ISSUE TITLE
Plugin Crashes on server start

### ISSUE THREAD

**Issue by lukeb2014** [j0ach1mmall3/UltimateCosmetics#192]
Hello there,
I purchased this plugin a couple days ago for a server a friend and I are trying to get up and running. When we installed the plugin, we got the following error in the console:

```
15.09 16:32:01 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
15.09 16:32:01 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:85) ~[?:?]
15.09 16:32:01 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.config.Config.<init>(Config.java:64) ~[?:?]
15.09 16:32:01 [Server] INFO at org.bukkit.Sound.valueOf(Sound.java:1) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
15.09 16:32:01 [Server] INFO at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_101]
15.09 16:32:01 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_CHEST_OPEN
15.09 16:32:01 [Server] ERROR Error occurred while enabling UltimateCosmetics v4.2.3 (Is it up to date?)
```
JLib is successfully installed and runs without errors. We have ProtocolLib installed--the server is running Spigot 1.8 (and 1.7 via ProtocolSupport). I also set in the config file all options that are 1.8+ to false.

Any idea why it's not working?
Thank you,
Luke Baird

**Comment by j0ach1mmall3** [comment]
Install the 1.8 configs

**Comment by lukeb2014** [comment]
I got it working, thank you. Sorry I didn't close the issue
