### ISSUE TITLE
All NPE's

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#36]
Plugin version 3.6.3
Server version 1.8.3 R0.1
Server type (Spigot)
Every single config file the default config just when I installed it.
Plugins list https://gyazo.com/74ef791112d01e752acb21447a51784b
Console log/Crash Report/...

I opened the inventory, then when I clicked on any of the items I get NPE's

**Comment by 99IRock** [comment]
[22:16:39] [Server thread/INFO]: ThomasssMC issued server command: /balloons
[22:16:44] [Server thread/ERROR]: Could not pass event InventoryClickEvent to UltimateCosmetics v3.6.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1620) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-870264a-0a645a2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [server.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.j0ach1mmall3.ultimatecosmetics.internal.gui.GadgetsGuiHandler.handleClick(GadgetsGuiHandler.java:94) ~[?:?]
	at com.j0ach1mmall3.ultimatecosmetics.internal.gui.GuiHandler.onInventoryClick(GuiHandler.java:76) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[server.jar:git-Spigot-870264a-0a645a2]
	... 15 more

**Comment by j0ach1mmall3** [comment]
Weird, it all works perfectly for me. What items are you clicking? Are your configs all default?

**Comment by 99IRock** [comment]
I updated the spigot to 1.8.8 and now I don't have any NPE's anymore :+1: 
And yes the config was default.
It was any item.
I also didnt get the Cosmetic chest.

**Comment by j0ach1mmall3** [comment]
Ok
