### ISSUE TITLE
[Help Requested] Small Amount of Compilation Errors

### ISSUE THREAD

**Issue by TheDiamondPicks** [j0ach1mmall3/UltimateCosmetics#39]
I have compiled the source however I have received a few errors at startup.
```
java.lang.Error: Unresolved compilation problems: 
	updateCheckerResult cannot be resolved to a variable
	Syntax error on tokens, delete these tokens
	updateCheckerResult cannot be resolved
	Syntax error, insert ")" to complete MethodInvocation
	Syntax error, insert ";" to complete Statement
	Syntax error on token "case", delete this token
	Syntax error on token "case", { expected
	Syntax error on token ")", { expected

	at com.j0ach1mmall3.ultimatecosmetics.Main.onEnable(Main.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot_server.jar:git-Spigot-fdc1440-880a532]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```
Any assistance would be greatly appreciated. I plan on purchasing your plugin in the near future but at the current stage I am unable to.

**Comment by j0ach1mmall3** [comment]
Make sure you're compiling with Java 8

**Comment by TheDiamondPicks** [comment]
Re-compiled with Java 8 and I still receive the same errors

**Comment by j0ach1mmall3** [comment]
Make sure you have all the dependencies added to your classpath

**Comment by j0ach1mmall3** [comment]
Is this fixed?

**Comment by TheDiamondPicks** [comment]
Apologies, I've been away from my PC and have been unable to reply. I have not resolved this error.
I have the following dependencies:
JLib
Spigot
and LibsDisguises.
Are there any additional ones I need to compile the plugin?

**Comment by j0ach1mmall3** [comment]
ProtocolLib

**Comment by TheDiamondPicks** [comment]
Added ProtocolLib and I still receive these errors. Any ideas?

**Comment by j0ach1mmall3** [comment]
Eh not reall, the only thing I can think of is java. Try compiling the latest ultimatecosmetics, that one has java 7 support
