### ISSUE TITLE
Plugin not loading.

### ISSUE THREAD

**Issue by yetshadow** [j0ach1mmall3/UltimateCosmetics#46]
Version 3.7.0
Server version Spigot 1.8.7-R0.1-SNAPSHOT
Server Spigot
Log:
[01:30:10] [Server thread/ERROR]: Could not load 'plugins/UltimateCosmetics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/ultimatecosmetics/Main : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]
Caused by: java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/ultimatecosmetics/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0]
	at java.lang.Class.forName(Class.java:264) ~[?:1.7.0]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]
	... 6 more

**Comment by yetshadow** [comment]
Fixed by removing RToolKit
