### ISSUE TITLE
Player left event Warn with logs

### ISSUE THREAD

**Issue by yetshadow** [j0ach1mmall3/UltimateCosmetics#64]
[22:52:41] [Craft Scheduler Thread - 347/WARN]: java.lang.NullPointerException: Nodes must be provided.
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at com.j0ach1mmall3.jlib.storage.file.yaml.Config.saveConfig(Config.java:55)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.updateQueue(FileDataLoader.java:89)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$4.run(PlayerListener.java:208)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
[22:52:41] [Craft Scheduler Thread - 347/WARN]: 	at java.lang.Thread.run(Thread.java:722)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: java.lang.NullPointerException
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:400)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.access$1600(Emitter.java:62)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingSimpleValue.expect(Emitter.java:641)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:216)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:181)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:206)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at com.j0ach1mmall3.jlib.storage.file.yaml.Config.saveConfig(Config.java:55)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.updateQueue(FileDataLoader.java:89)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$5.run(PlayerListener.java:222)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
[22:52:41] [Craft Scheduler Thread - 346/WARN]: 	at java.lang.Thread.run(Thread.java:722)
[22:52:41] [Server thread/WARN]: handleDisconnection() called twice

Not every time but, it happen often, not a big bug too.

Spigot 1.8.8
Java 8
Rtoolkit
Offline mode

**Comment by j0ach1mmall3** [comment]
Pastebin it please

**Comment by j0ach1mmall3** [comment]
Also, you can try using SQLite instead of File for data storage, it might help
