### ISSUE TITLE
What does it mean? This spam in my console.

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#70]
[12:10:52 INFO]: [JLib] WARNING: I'm using deprecated method com.j0ach1mmall3.jlib.storage.database.mongodb.MongoDB.getObject(MongoDB.java:106) at com.j0ach1mmall3.jlib.storage.database.mongodb.MongoDB$5.run(MongoDB.java:180)!

**Comment by j0ach1mmall3** [comment]
Aha, great, leme see what I can do about that

**Comment by Toshka17** [comment]
Spamming in console if using gadjets

[10:24:04 INFO]: [JLib] WARNING: I'm using deprecated method com.j0ach1mmall3.jlib.methods.ReflectionAPI.getHandle(ReflectionAPI.java:99) at com.j0ach1mmall3.jlib.methods.ReflectionAPI.sendPacket(ReflectionAPI.java:161)!

**Comment by Toshka17** [comment]
For different gadjets - different warnings

[10:27:00 INFO]: [JLib] WARNING: I'm using deprecated method com.j0ach1mmall3.jlib.methods.General.broadcastSound(General.java:96) at com.j0ach1mmall3.ultimatecosmetics.internal.gadgets.GadgetsListener$17.run(GadgetsListener.java:542)!
