### ISSUE TITLE
Again error. (Yes i have the new version!)

### ISSUE THREAD

**Issue by RobinArnhardt** [j0ach1mmall3/UltimateCosmetics#78]
Error:

[04:09:53] [Craft Scheduler Thread - 48/WARN]: java.lang.NullPointerException: Nodes must be provided.
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at com.j0ach1mmall3.jlib.storage.file.yaml.Config.saveConfig(Config.java:82)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.updateQueue(FileDataLoader.java:127)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$4.run(PlayerListener.java:209)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[04:09:53] [Craft Scheduler Thread - 48/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[04:09:53] [Server thread/WARN]: handleDisconnection() called twice

Please fix it.... Thanks...

**Comment by j0ach1mmall3** [comment]
1. Pastebin
2. /uc debug
