### ISSUE TITLE
Serious Issue Crashed My Server!

### ISSUE THREAD

**Issue by TheFemoDemo** [j0ach1mmall3/UltimateCosmetics#85]
**This error popped up and just as it did HUGE amounts of lag occurred and the server crashed!**

[18:02:08] [Craft Scheduler Thread - 710/ERROR]: Cannot load plugins/UltimateCosmetics/data.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
in 'string', line 4, column 1:
Ammo:
^
expected , but found BlockMappingStart
in 'string', line 2490, column 3:
29df61f9-dadb-4ac9-8e5d-ca138812 ... 
^

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at com.j0ach1mmall3.jlib.storage.file.yaml.Config.getConfig(Config.java:64) [JLib.jar:?]
at com.j0ach1mmall3.jlib.storage.file.yaml.Config.getKeys(Config.java:139) [JLib.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.createAmmo(FileDataLoader.java:110) [UltimateCosmetics.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.unloadAmmo(FileDataLoader.java:44) [UltimateCosmetics.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$5.run(PlayerListener.java:224) [UltimateCosmetics.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'string', line 4, column 1:
Ammo:
^
expected , but found BlockMappingStart
in 'string', line 2490, column 3:
29df61f9-dadb-4ac9-8e5d-ca138812 ... 
^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
... 13 more
[18:02:08] [Craft Scheduler Thread - 710/ERROR]: Cannot load plugins/UltimateCosmetics/data.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
in 'string', line 4, column 1:
Ammo:
^
expected , but found BlockMappingStart
in 'string', line 2490, column 3:
29df61f9-dadb-4ac9-8e5d-ca138812 ... 
^

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at com.j0ach1mmall3.jlib.storage.file.yaml.Config.getConfig(Config.java:64) [JLib.jar:?]
at com.j0ach1mmall3.jlib.storage.file.yaml.Config.getKeys(Config.java:139) [JLib.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.createAmmo(FileDataLoader.java:110) [UltimateCosmetics.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader.unloadAmmo(FileDataLoader.java:44) [UltimateCosmetics.jar:?]
at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$5.run(PlayerListener.java:224) [UltimateCosmetics.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'string', line 4, column 1:
Ammo:
^
expected , but found BlockMappingStart
in 'string', line 2490, column 3:
29df61f9-dadb-4ac9-8e5d-ca138812 ... 
^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
... 13 more

**Comment by j0ach1mmall3** [comment]
Pastebin the error an your data.yml
/uc debug

**Comment by TheFemoDemo** [comment]
https://gist.github.com/anonymous/e276a063217ae759d680

**Comment by TheFemoDemo** [comment]
The error just happened again. I had to wait for it so that I could run /uc debug! Sorry for the wait!

**Comment by TheFemoDemo** [comment]
[20:31:04] [Craft Scheduler Thread - 519/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltimateCosmetics v3.10.3 generated an exception while executing task 126227
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader$1.setOffline(FileDataLoader.java:31)
at com.j0ach1mmall3.ultimatecosmetics.internal.data.FileDataLoader$1.setOffline(FileDataLoader.java:19)
at com.j0ach1mmall3.jlib.storage.Cache.unload(Cache.java:43)
at com.j0ach1mmall3.ultimatecosmetics.internal.listeners.PlayerListener$4.run(PlayerListener.java:213)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

[20:31:04] [Server thread/WARN]: handleDisconnection() called twice

**Comment by TheFemoDemo** [comment]
That's what appeared in the console!

**Comment by TheFemoDemo** [comment]
http://pastebin.com/YFUVFMjH

**Comment by j0ach1mmall3** [comment]
Can you upload your data.yml?

**Comment by TheFemoDemo** [comment]
http://pastebin.com/GFq94eBV

**Comment by TheFemoDemo** [comment]
Sorry for the late response. I have been quite busy.
